version: '3.7'
services:
    db:
        image: mysql/mysql-server:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'us_legislation'
            MYSQL_USER: 'dbadmin'
            MYSQL_PASSWORD: '123456789'
        volumes:
            - data_volume:/var/lib/mysql
#            - ./my.cnf:/etc/mysql/my.cnf
    phpmyadmin:
        image: phpmyadmin:5.2.0
        restart: always
        ports:
            - "9103:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: 'db'
            PMA_USER: 'dbadmin'
            PMA_PASSWORD: '123456789'
        depends_on:
            - db
volumes:
    data_volume: