version: '3.7'
services:
    db:
        image: mysql/mysql-server:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'qavanin'
            MYSQL_USER: 'dbadmin'
            MYSQL_PASSWORD: '123456789'
        volumes:
            - my-datavolume:/var/lib/mysql
#            - ./my.cnf:/etc/mysql/my.cnf
    phpmyadmin:
        image: phpmyadmin
#        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: 'model'
            PMA_USER: 'dbadmin'
            PMA_PASSWORD: '123456789'
        depends_on:
            - db
volumes:
    my-datavolume: